name: Cryptic Reptiles
favicon: null
layout_spectrum: 0.4271057010628283
typography_spectrum: 0.542678534751758
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d283f'
    - '#f7e9e1'
    - '#c7856d'
    - '#95212d'
    - '#7da0a1'
  brandStrength: 0.1875
  lightness: 0.9204847810324281
  saturation: 0.8287875836249441
  rhythmicContrast: 0.5741937765851617
purpose: []
